#!/bin/bash
#Обновление скрипта запуска Teamtalk сервера!
#Теперь можно указать аргумент командной строки и сервер создаётся в корневой папке пользователя желательно.
#Требуется lsof для проверки порта по занятому сегменту процесса tt5srv
#Шаблонный файл config.xml может быть изменён по вашему желанию, но некоторые пораметры изменять нельзя, так как они привязаны к скрипту.
usage() {
  echo "Использование: После каждого параметра указывайте английское название имени"
  echo "Опции:"
  echo "  -c затем имя, создаёт всё для сервера и запускает его"
  echo "  -s затем имя останавливает сервер и выключает из автозагрузки"
  echo "  -S заглавная: запускает сервер и добавляет его в автозагрузку"
  echo "  -u имя англ: удаляет TeamTalk сервер полностью с файлами и systemd сервисом"
  echo ""
  echo "Внимание! все параметры указываются с дефисом"
  echo "для примера: tt5-set -c new-server. Создаёт сервер с папкой new-server и добавляет юнит new-server.service"
  echo "по анологии также с другими параметрами."
  exit 1
}

while getopts ":c:s:S:u:" opt; do
  case ${opt} in
    c )
      FN=$OPTARG
      mkdir -p $FN/files
      server="teamtalk"
      user="admin"
      pass="admin"

      busy_ports=$(lsof -i | grep tt5srv | awk '{print $9}' | cut -d : -f 2)
      start_port=20000
      end_port=30000

      for port in $(seq $start_port $end_port); do
          if ! echo $busy_ports | grep -q "\<$port\>"; then
              tcp=$port
              udp=$port
              break
          fi
      done

      source /usr/local/bin/config.xml
	  
	  if [ -d .config/systemd/user ]; then
	  sleep 1
else
mkdir -p $HOME/.config/systemd/user
fi
      echo "[Unit]
Description=tt5
After=network.target

[Service]
ExecStart=/usr/local/bin/tt5srv -wd $FN -nd

[Install]
WantedBy=default.target" > $HOME/.config/systemd/user/$FN.service
      systemctl --user daemon-reload
      systemctl --user enable $FN
      systemctl --user start $FN
      echo "Система выделила вам порт: $port"
      echo "Внимание! Доступ администратора по данным admin admin. Обязательно измените пароль и логин!"
      ;;
    s )
      FN=$OPTARG
      systemctl --user stop $FN
      systemctl --user disable $FN
      echo "Сервер остановлен"  
      ;;
    S )
      FN=$OPTARG
      systemctl --user enable $FN
      systemctl --user start $FN
      echo "Сервер запущен"
      ;;
    u )
                FN=$OPTARG
                systemctl --user stop $FN
                systemctl --user disable $FN
                rm -R $FN
                rm $HOME/.config/systemd/user/$FN.service
				echo "Вы удалили TeamTalk сервер! Файлов больше нет."
                                 ;;
    \? )
      echo "Вариант непонятен: -$OPTARG" 1>&2
      usage
      ;;
    : )
      echo "Неверные данные: -$OPTARG требует имя" 1>&2
      usage
      ;;
    * )
      usage
      ;;
  esac
done

if [ $OPTIND -eq 1 ]; then
  usage
fi
